/* ============================================================
   Solar System — mobile bottom navigation
   ------------------------------------------------------------
   A thumb-reachable tab bar for touch/small screens, plus one shared bottom
   sheet for the two tabs that open a list.

   Why this exists: on a phone the topbar wrapped to two or three rows -- up to
   ~180px, over a fifth of the screen -- because five pills plus a wordmark do
   not fit in 334px. It also sat at the very top, the hardest place to reach
   one-handed on a large phone, and in-page anchors after the first were hidden
   outright, so the landing's own sections had no nav representation at all.

   Built in JS and injected, rather than authored into all twelve pages: the
   eight planet pages are generated by scripts/build-planets.js and cannot be
   regenerated locally (no Node), so every hand-edit to them is a drift risk.
   One <script> line per page carries no such risk. The bar is an enhancement --
   without JS the topbar remains, and every destination here is reachable from
   it or by scrolling.

   Deliberately a classic script with no imports, matching the rest of the site
   (pages must keep working from file://).
   ============================================================ */
(function () {
  "use strict";

  var body = document.body;
  if (!body || document.querySelector(".tabbar")) return;

  /* Depth-aware paths. The site is served from a project subpath
     (/Solar-System-Exploration/), so absolute paths would 404; planet pages sit
     one level down. Same approach as js/backlink.js. */
  var P = /\/planet\//.test(location.pathname) ? "../" : "";
  var here = location.pathname.replace(/\/+$/, "").split("/").pop() || "index.html";

  var PLANETS = [
    ["mercury", "Mercury"], ["venus", "Venus"], ["earth", "Earth"], ["mars", "Mars"],
    ["jupiter", "Jupiter"], ["saturn", "Saturn"], ["uranus", "Uranus"], ["neptune", "Neptune"],
  ];
  var ARTICLES = [
    ["formation.html", "How it all began", "The Solar System's first 100 million years"],
    ["exploration.html", "Fifty years beyond Earth", "What we have sent, and what it found"],
    ["instruments.html", "The machines that saw it", "The telescopes and probes behind the data"],
  ];

  function icon(d) {
    return '<svg viewBox="0 0 24 24" width="22" height="22" fill="none" aria-hidden="true">' +
      '<path d="' + d + '" stroke="currentColor" stroke-width="1.7" ' +
      'stroke-linecap="round" stroke-linejoin="round"/></svg>';
  }
  var ICONS = {
    map: "M12 4a8 8 0 1 0 0 16 8 8 0 0 0 0-16Zm0 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5Z",
    planets: "M5 12a7 7 0 1 0 14 0 7 7 0 0 0-14 0Zm-2.2 2.6c3.6 2 12 3 18.4-1.6",
    learn: "M4 5.5h6a2 2 0 0 1 2 2v11a1.6 1.6 0 0 0-1.6-1.6H4Zm16 0h-6a2 2 0 0 0-2 2v11a1.6 1.6 0 0 1 1.6-1.6H20Z",
    search: "M10.5 4a6.5 6.5 0 1 0 0 13 6.5 6.5 0 0 0 0-13Zm4.6 11.1L20 20",
  };

  /* ── the bar ─────────────────────────────────────────────── */
  var bar = document.createElement("nav");
  bar.className = "tabbar";
  bar.setAttribute("aria-label", "Primary, mobile");
  bar.innerHTML =
    '<a class="tabbar__item" href="' + P + 'index.html#menu" data-tab="map">' +
      icon(ICONS.map) + "<span>Map</span></a>" +
    '<button class="tabbar__item" type="button" data-sheet="planets">' +
      icon(ICONS.planets) + "<span>Planets</span></button>" +
    '<button class="tabbar__item" type="button" data-sheet="learn">' +
      icon(ICONS.learn) + "<span>Learn</span></button>" +
    '<button class="tabbar__item" type="button" data-search>' +
      icon(ICONS.search) + "<span>Search</span></button>";
  body.appendChild(bar);

  /* ── the shared sheet ────────────────────────────────────────
     A native <dialog>: focus trapping, Escape, a backdrop and focus
     restoration all come for free, exactly as js/sections.js reasons about
     the mission dialog. Reimplementing those four badly is the usual cost of
     a hand-rolled sheet. */
  var sheet = document.createElement("dialog");
  sheet.className = "sheet";
  sheet.setAttribute("aria-labelledby", "sheetTitle");
  sheet.innerHTML =
    '<div class="sheet__grip" aria-hidden="true"></div>' +
    '<h2 class="sheet__title" id="sheetTitle"></h2>' +
    '<div class="sheet__body"></div>' +
    '<button class="sheet__close btn btn--ghost" type="button">Close</button>';
  body.appendChild(sheet);
  var sheetTitle = sheet.querySelector(".sheet__title");
  var sheetBody = sheet.querySelector(".sheet__body");

  function planetRows() {
    return PLANETS.map(function (p, i) {
      var current = here === p[0] + ".html" ? ' aria-current="page"' : "";
      return '<a class="sheet__row" href="' + P + "planet/" + p[0] + '.html"' + current + ">" +
        '<span class="sheet__dot" data-planet="' + p[0] + '"></span>' +
        '<span class="sheet__label">' + p[1] + "</span>" +
        '<span class="sheet__meta">' + (i + 1) + " from the Sun</span></a>";
    }).join("");
  }
  function articleRows() {
    return ARTICLES.map(function (a) {
      var current = here === a[0] ? ' aria-current="page"' : "";
      return '<a class="sheet__row sheet__row--stack" href="' + P + a[0] + '"' + current + ">" +
        '<span class="sheet__label">' + a[1] + "</span>" +
        '<span class="sheet__meta">' + a[2] + "</span></a>";
    }).join("");
  }

  function openSheet(kind) {
    sheetTitle.textContent = kind === "planets" ? "The eight planets" : "Go deeper";
    sheetBody.innerHTML = kind === "planets" ? planetRows() : articleRows();
    if (sheet.showModal) sheet.showModal();
    else sheet.setAttribute("open", "");
  }
  function closeSheet() {
    if (sheet.close) sheet.close();
    else sheet.removeAttribute("open");
  }

  bar.addEventListener("click", function (e) {
    var btn = e.target.closest("[data-sheet]");
    if (btn) { openSheet(btn.getAttribute("data-sheet")); return; }
    /* Looked up at CLICK time, not at load time, so this file does not care
       whether js/search.js has run yet. On a phone there is no keyboard to
       press "/" on, so this tab is the only way in. */
    if (e.target.closest("[data-search]") && window.SolarSearch) {
      window.SolarSearch.open();
    }
  });
  sheet.addEventListener("click", function (e) {
    if (e.target.closest(".sheet__close")) { closeSheet(); return; }
    /* Backdrop only. e.target === dialog is ALSO true for clicks on the
       dialog's own padding, so hit-test the border box -- the same trap
       js/sections.js hit with the mission dialog. */
    if (e.target !== sheet || !e.detail) return;
    var r = sheet.getBoundingClientRect();
    if (e.clientX < r.left || e.clientX > r.right || e.clientY < r.top || e.clientY > r.bottom) {
      closeSheet();
    }
  });

  /* Mark the Map tab current on the landing page. The sheets carry their own
     aria-current on the row that matches this page. */
  if (here === "index.html" || here === "") {
    var mapTab = bar.querySelector('[data-tab="map"]');
    if (mapTab) mapTab.setAttribute("aria-current", "page");
  }

  /* Explorer mode takes over the whole screen and hides the topbar; the tab bar
     would sit on top of the map. body.is-exploring is toggled by
     js/explorer.js, so watch the class rather than duplicating its logic. */
  if (window.MutationObserver) {
    new MutationObserver(function () {
      bar.hidden = body.classList.contains("is-exploring");
      if (bar.hidden && sheet.open) closeSheet();
    }).observe(body, { attributes: true, attributeFilter: ["class"] });
  }
})();
